baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

## Site Settings
[params]
logo = ""
favicon = "favicon.ico"
custom_css = []
custom_js = []

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
